version: "3.8"

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: todo-list
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
