version: "3.8"

services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: Your-Times
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
